step 1 : Import Libraries

In [3]:
import pandas as pd
print("Libraries imported successfully!!")

Libraries imported successfully!!

step 2 : Load csv dataset

In [4]:
df = pd.read_csv('student_performance.csv')
print("Dataset loaded successfully!!")

Dataset loaded successfully!!

step 3 : view the first few rows

In [5]:
df.head()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

step 4: view the last 5 rows

In [6]:
df.tail()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

step 5

In [7]:
print("Number of rows and columns:",df.shape)
print("Number of students(row):",df.shape[0])
print("Number of columns:",df.shape[1])

Number of rows and columns: (30, 13)
Number of students(row): 30
Number of columns: 13

step 6 : see all column names

In [8]:
print("columns in the dataset:")
print(df.columns.tolist())

columns in the dataset:
['student_id', 'name', 'age', 'gender', 'department', 'semester', 'math_score', 'science_score', 'english_score', 'programming_score', 'attendance_percentage', 'city', 'admission_year']

in this it prints in line by line

In [9]:
df.columns.tolist()

['student_id',
 'name',
 'age',
 'gender',
 'department',
 'semester',
 'math_score',
 'science_score',
 'english_score',
 'programming_score',
 'attendance_percentage',
 'city',
 'admission_year']

step 7:statistical summary

In [10]:
print("data types:")
print(df.dtypes)

data types:
student_id                int64
name                     object
age                       int64
gender                   object
department               object
semester                  int64
math_score                int64
science_score             int64
english_score             int64
programming_score         int64
attendance_percentage     int64
city                     object
admission_year            int64
dtype: object

In [11]:
df.describe()

,student_id,age,semester,math_score,science_score,english_score,programming_score,attendance_percentage,admission_year
count,30.000000,30.000000,30.0,30.000000,30.000000,30.000000,30.000000,30.000000,30.0
mean,1015.500000,19.733333,2.0,76.066667,77.833333,74.166667,67.600000,84.500000,2023.0
std,8.803408,0.739680,0.0,11.467896,8.554423,10.003735,21.041175,9.379913,0.0
min,1001.000000,19.000000,2.0,56.000000,61.000000,55.000000,38.000000,65.000000,2023.0
25%,1008.250000,19.000000,2.0,67.250000,71.250000,67.250000,49.250000,77.250000,2023.0
50%,1015.500000,20.000000,2.0,75.500000,78.000000,75.000000,66.000000,86.500000,2023.0
75%,1022.750000,20.000000,2.0,85.750000,83.750000,81.750000,88.750000,91.750000,2023.0
max,1030.000000,21.000000,2.0,95.000000,93.000000,90.000000,97.000000,98.000000,2023.0

step 8 :check the missing values

In [12]:
print("Missing values in each column:")
print(df.isnull().sum())
print("\nTotal missing values:",df.isnull().sum().sum())

Missing values in each column:
student_id               0
name                     0
age                      0
gender                   0
department               0
semester                 0
math_score               0
science_score            0
english_score            0
programming_score        0
attendance_percentage    0
city                     0
admission_year           0
dtype: int64

Total missing values: 0

step 9 : explore specific columns

In [13]:
print("Students Names:")
print(df['name'])

Students Names:
0       Aarav Sharma
1        Priya Patel
2        Rohit Verma
3        Sneha Reddy
4         Arjun Nair
5        Meera Joshi
6        Kiran Kumar
7        Divya Singh
8       Rahul Mishra
9         Ananya Das
10       Vikram Iyer
11       Pooja Gupta
12        Suresh Rao
13     Kavya Nambiar
14       Ajay Tiwari
15      Ritu Agarwal
16      Manoj Pandey
17    Swati Kulkarni
18    Deepak Chauhan
19      Nisha Kapoor
20     Harish Pillai
21       Tanvi Mehta
22      Sanjay Dubey
23     Preeti Saxena
24         Amit Bose
25        Rekha Nair
26     Gaurav Shukla
27     Sunita Pillai
28        Nitin Jain
29    Akanksha Yadav
Name: name, dtype: object

In [14]:
print("Students age:")

print(df['age'])

Students age:
0     19
1     20
2     19
3     20
4     19
5     20
6     21
7     19
8     20
9     19
10    20
11    19
12    21
13    20
14    19
15    20
16    21
17    19
18    20
19    19
20    20
21    19
22    21
23    20
24    19
25    20
26    21
27    19
28    20
29    19
Name: age, dtype: int64

view unique departments

In [15]:
print("departments in the dataset:")
print(df['department'].unique())
print("\nHow many students per department:")
print(df['department'].value_counts())

departments in the dataset:
['Computer Science' 'Electronics' 'Mechanical' 'Civil']

How many students per department:
department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64

step 10 : filtering the data

In [16]:
cs_students = df[df['department'] == 'Computer Science']
print(f"Number of computer science students:{len(cs_students)}")
print("\nComputer science students:")
print(cs_students[['name','math_score','programming_score','attendance_percentage']])

Number of computer science students:13

Computer science students:
              name  math_score  programming_score  attendance_percentage
0     Aarav Sharma          85                 91                     92
1      Priya Patel          76                 79                     87
4       Arjun Nair          92                 95                     90
7      Divya Singh          88                 93                     96
9       Ananya Das          95                 97                     98
12      Suresh Rao          83                 88                     88
14     Ajay Tiwari          71                 76                     75
17  Swati Kulkarni          90                 92                     94
19    Nisha Kapoor          79                 83                     89
21     Tanvi Mehta          93                 96                     97
24       Amit Bose          86                 89                     91
26   Gaurav Shukla          84                 87                     87
29  Akanksha Yadav          91                 94                     95

filtering students with high attendance (above 90)

In [17]:
high_attendance = df[df['attendance_percentage']>90]
print(f"Students with attendance above 90%: {len(high_attendance)}")
print(high_attendance[['name','department','attendance_percentage']])

Students with attendance above 90%: 10
              name        department  attendance_percentage
0     Aarav Sharma  Computer Science                     92
3      Sneha Reddy        Mechanical                     95
7      Divya Singh  Computer Science                     96
9       Ananya Das  Computer Science                     98
13   Kavya Nambiar        Mechanical                     91
15    Ritu Agarwal       Electronics                     93
17  Swati Kulkarni  Computer Science                     94
21     Tanvi Mehta  Computer Science                     97
24       Amit Bose  Computer Science                     91
29  Akanksha Yadav  Computer Science                     95

step 11 : find the top performing student

In [18]:
df['total_score'] = df['math_score'] + df['science_score'] + df['english_score'] + df['programming_score']
top_student = df.loc[df['total_score'].idxmax()]
print("Top Students:")
print(f"Name:{top_student['name']}")
print(f"department:{top_student['department']}")
print(f"Total Score:{top_student['total_score']}")
print(f"Attendance:{top_student['attendance_percentage']}%")

Top Students:
Name:Ananya Das
department:Computer Science
Total Score:371
Attendance:98%

calculate avg score per dept

In [19]:
dept_avg = df.groupby('department')['total_score'].mean().round(2)
print("Average Total Scores per Department:")
print(dept_avg)

Average Total Scores per Department:
department
Civil               235.80
Computer Science    340.15
Electronics         277.50
Mechanical          267.33
Name: total_score, dtype: float64

step 12 : sort students by total score HIGH - LOW

In [20]:
df_sorted = df.sort_values(by='total_score',ascending=False)
print("Top 10 students by total score:")
print(df_sorted[['name','department','total_score','attendance_percentage']].head(10))

Top 10 students by total score:
              name        department  total_score  attendance_percentage
9       Ananya Das  Computer Science          371                     98
21     Tanvi Mehta  Computer Science          367                     97
29  Akanksha Yadav  Computer Science          365                     95
4       Arjun Nair  Computer Science          356                     90
7      Divya Singh  Computer Science          356                     96
17  Swati Kulkarni  Computer Science          354                     94
24       Amit Bose  Computer Science          336                     91
12      Suresh Rao  Computer Science          334                     88
19    Nisha Kapoor  Computer Science          327                     89
0     Aarav Sharma  Computer Science          326                     92

PRACTICE QUESTIONS




How many students are from the electronics department?

In [21]:
ed_students = df[df['department'] == 'Electronics']
print(f"Number of Electronics students:{len(ed_students)}")

Number of Electronics students:6

what is the average attendance of female students?

In [22]:
female_students = df[df['gender']=='Female']
avg = female_students['attendance_percentage'].mean()
print(f"Avg female students:{avg}%")

Avg female students:88.53333333333333%

who is the student with the lowest programming score?

In [23]:
Low = df[df['programming_score']<40]
print(f"Students lowest score: {len(Low)}")
print(Low[['name','department','attendance_percentage']])

Students lowest score: 2
             name department  attendance_percentage
16   Manoj Pandey      Civil                     65
27  Sunita Pillai      Civil                     73

how many students scored above 80 in math?

In [24]:
std = df[df['math_score']>80]
print(f"Students with attendance above 80%: {len(std)}")
print(std[['name','department','attendance_percentage']])

Students with attendance above 80%: 11
              name        department  attendance_percentage
0     Aarav Sharma  Computer Science                     92
4       Arjun Nair  Computer Science                     90
7      Divya Singh  Computer Science                     96
9       Ananya Das  Computer Science                     98
12      Suresh Rao  Computer Science                     88
15    Ritu Agarwal       Electronics                     93
17  Swati Kulkarni  Computer Science                     94
21     Tanvi Mehta  Computer Science                     97
24       Amit Bose  Computer Science                     91
26   Gaurav Shukla  Computer Science                     87
29  Akanksha Yadav  Computer Science                     95

what is the average total_score for students with attendance above 90%?

In [27]:
std = df[df['attendance_percentage']>90]
avg = std['total_score'].mean()
print(f'student avg attendance above 90:{avg}')

student avg attendance above 90:335.8

MINI PROJECT:Student Data ExplorerObjective:
Create a Student Performance Explorer using Python and Pandas to analyze student data and generate a detailed report .

Dataset Columns:
name
gender
department
math_score
programming_score
attendance_percentage
total_score

Tasks to Perform:
1.Display Project Title
2.Dataset Objective
Display:
-Total number of students
-Total number of columns
-Number of unique departments
3.Department-wise Analysis
Display the count of students in each department.
4.Score Analysis
Find and Display:
-Highest math score
-Lowest math score
-Average math score
-Average Programming score
-Average attendance percentage
5.Gender wise Analysis
Calculate and display average total score grouped by gender.
6.Top performers
Display the top 5 students based on total_Score.
Show:
-Student Name
-Department
-Total Score
7.Attendance Analysis
Find Students whose attendance is below 75%
Display:
-Name
-Department
-Attendance Percentage
If all students have attendance above 75%
print a suitable message.
Concepts to Use:
-pandas,Dataframe,groupby(),value_counts(),mean(),max(),min(),sort_values(),iterows(),Conditional statements,f-strings

In [38]:
print('-----------------------------------------------------')
print('             [1]Student Data Explorer')
print('------------------------------------------------------')

print('--------------------------------------------')
print('         [2] Dataset Objective')
print('--------------------------------------------')

print("Total Number of Students :",len(df))
# print(len(df))
print("Total Number of Columns:",df.shape[1])
# print(df.shape[1])
# print("Number of unique departments")
print("Number of unique departments :",df['department'].nunique())

print('--------------------------------------------')
print('         [3] Department-wise Analysis ')
print('--------------------------------------------')

print("Number of Students per department")
print(df['department'].value_counts())

print('--------------------------------------------')
print('         [4] Score Analysis')
print('--------------------------------------------')

high_math=df['math_score'].max()
print(f'Highest math score:{high_math}')
low_math=df['math_score'].min()
print(f'Lowest math score:{low_math}')
avg_math=df['math_score'].mean()
print(f'Average math score:{avg_math}')
avg_prog=df['programming_score'].mean()
print(f'Avergae Programming Score:{avg_prog}')
avg_att=df['attendance_percentage'].mean()
print(f'Average Attendance Percentage:{avg_att}')

print('--------------------------------------------')
print('         [5] Gender wise Analysis')
print('--------------------------------------------')

gender_avg=df.groupby('gender')['total_score'].mean().round(2)
print(f"Average Total Score grouped by gender:{gender_avg}")

print('--------------------------------------------')
print('         [6] Top performers')
print('--------------------------------------------')

df_sorted=df.sort_values(by='total_score',ascending=False)
print("Top 5 students by total score")
print(df_sorted[['name','department','total_score']].head(5))

print('--------------------------------------------')
print('         [7] Attendance Analysis')
print('--------------------------------------------')

low_att=df[df['attendance_percentage']<75]
print("Students with low attendance percentage:")
print(low_att[['name','department','attendance_percentage']])

-----------------------------------------------------
             [1]Student Data Explorer
------------------------------------------------------
--------------------------------------------
         [2] Dataset Objective
--------------------------------------------
Total Number of Students : 30
Total Number of Columns: 14
Number of unique departments : 4
--------------------------------------------
         [3] Department-wise Analysis
--------------------------------------------
Number of Students per department
department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64
--------------------------------------------
         [4] Score Analysis
--------------------------------------------
Highest math score:95
Lowest math score:56
Average math score:76.06666666666666
Avergae Programming Score:67.6
Average Attendance Percentage:84.5
--------------------------------------------
         [5] Gender wise Analysis
--------------------------------------------
Average Total Score grouped by gender:gender
Female    310.67
Male      280.67
Name: total_score, dtype: float64
--------------------------------------------
         [6] Top performers
--------------------------------------------
Top 5 students by total score
              name        department  total_score
9       Ananya Das  Computer Science          371
21     Tanvi Mehta  Computer Science          367
29  Akanksha Yadav  Computer Science          365
4       Arjun Nair  Computer Science          356
7      Divya Singh  Computer Science          356
--------------------------------------------
         [7] Attendance Analysis
--------------------------------------------
Students with low attendance percentage:
             name   department  attendance_percentage
5     Meera Joshi  Electronics                     72
8    Rahul Mishra   Mechanical                     68
16   Manoj Pandey        Civil                     65
20  Harish Pillai  Electronics                     74
22   Sanjay Dubey        Civil                     70
27  Sunita Pillai        Civil                     73